# React Native Podfile
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '11.0' # Change this to your minimum iOS version

prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'LuxApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Ensure fonts from react-native-vector-icons are linked correctly
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  # Additional dependencies for your project
  # pod 'react-native-<some-package>', :path => '../node_modules/react-native-<some-package>'

  target 'LuxAppTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    # Workaround for an issue where some pods don't get properly linked
    installer.pods_project.targets.each do |target|
      if target.name == 'react-native-vector-icons'
        target.resources_build_phase.files.each do |file|
          file.remove_from_build_phase if file.display_name.include?(".ttf")
        end
      end
    end
  end
end
