export const colors = {
  primary: '#1c368a',
  secondary: '#94daff',
  accent: '#94daff',
  white: '#ffffff',
  text: '#808080',
  buttonText: '#ECFDF5',
  default: '#000',
  active: '#fff',
  gray: '#ccc',
  lightGray: '#f0f0f0',
  darkGray: '#d1d1d1',
  lightBlue: '#94daff',
  iconColor: '#FFFFFF',
  tabHoverColor: '#ffffff',
  notificationColor: '#94daff',
  bottomNavBgColor: '#1c368a',
  addButtonBgColor: '#94daff',
  addButtonBorderColor: '#ffff',
  iconColorBottomNav: '#fff',
};
